name: 📊 Atualizar Estatísticas README

on:
  schedule:
    - cron: '0 0 * * *'  # Executa diariamente à meia-noite
  workflow_dispatch:  # Permite executar manualmente

permissions:
  contents: write
  pull-requests: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Clonar repositório
        uses: actions/checkout@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name:  Fazer commit e push
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: '🔄 Atualizar estatísticas do README'
          commit_user_name: 'github-actions[bot]'
          commit_user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_options: '--no-verify'
          file_pattern: 'README.md'
